### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by baettigp** [Flydroid/ADS12xx-Library#1]
Hi,
as you have maybe seen, I forked your ADS12xx library in order to add the ADS1258 ADC. I wanted to ask you under which license (if any) you published your code, so I attach the correct conditions?

**Comment by Flydroid** [comment]
Hi Pio,

Thanks for the reminder 😊 And great that you want to add the ads1258.
Haven't gotten around to update the readme. Will do that tomorrow.
One thing I haven't done is handling the CS Line if you have multiple adc's
running.

Best Regards
Jonathan

**Comment by Flydroid** [comment]
I updated the license and my latest example. 
I just read your code and it looks like you managed fine with the integration. 
Especially the digitalPinToInterrupt function seems to be nice.

**Comment by baettigp** [comment]
I think the digitalpin to interrupt needs to be there to allow for other chips than the teensy (on which every pin is an interrupt pin) to work. could you please drop me an email? I have my address in my github profile? Herzlichen Dank.
