### ISSUE TITLE
#define STATUS - the same name of constantly was useed on ESP8266/ESP32

### ISSUE THREAD

**Issue by kamil2234** [Flydroid/ADS12xx-Library#5]
Hi,

I have problem with compilation on ESP8266/ESP32 boards.

This is my code:

`// Arudino Sample Code to use ADS1256 library
// Read 4 sensor using effiecient input cycling
// Written by Adien Akhmad, August 2015

#include <ADS1256.h>
#include <SPI.h>

byte DRDYPIN = 2;
byte CSPIN = 7;

// set pins
//#define SELPIN 7    // 
#define DATAOUT 12   //  MISO 
#define DATAIN 11    // MOSI
#define SPICLOCK 13  // 

float clockMHZ = 7.68; // crystal frequency used on ADS1256
int lo = 300;
float myarray[300];

// Define ADS1256 PIN that is connected to Arduino
ADS1256 adc(clockMHZ,DRDYPIN,CSPIN,2.5); // RESETPIN is permanently tied to 3.3v

/* Variable to store sensor reading
  sensor1 = connected on AIN0 - AIN1
  sensor2 = connected on AIN2 - AIN3
  sensor3 = connected on AIN4 - AIN5
  sensor4 = connected on AIN6 - AIN7
*/

float sensor1, sensor2, sensor3, sensor4;

void setup()
{
  Serial.begin(9600);
  delay(10000);
  Serial.println("Starting ADC");
  delay(1000);
// rozdzielczość
//PGAmulti_1    0.0000005960464832810452   //PGA-1  ±5V        /16777215  
//PGAmulti_2    0.0000002980232416405226   //PGA-2  ±2.5V      /16777215  
//PGAmulti_4    0.0000001490116208202613   //PGA-4  ±1.25V     /16777215  
//PGAmulti_8    0.00000007450581041013064  //PGA-8  ±0.625V    /16777215  
//PGAmulti_16   0.00000003725290520506532  //PGA-16 ±312.5mV   /16777215  
//PGAmulti_32   0.00000001862645260253266  //PGA-32 ±156.25mV  /16777215  
//PGAmulti_64   0.000000009313226301266331 //PGA-64 ±78.125mV  /16777215  
  

  // start the ADS1256 with data rate of 15 SPS
  // other data rates: 
  // ADS1256_DRATE_30000SPS
  // ADS1256_DRATE_15000SPS
  // ADS1256_DRATE_7500SPS
  // ADS1256_DRATE_3750SPS
  // ADS1256_DRATE_2000SPS
  // ADS1256_DRATE_1000SPS
  // ADS1256_DRATE_500SPS
  // ADS1256_DRATE_100SPS
  // ADS1256_DRATE_60SPS
  // ADS1256_DRATE_50SPS
  // ADS1256_DRATE_30SPS
  // ADS1256_DRATE_25SPS
  // ADS1256_DRATE_15SPS
  // ADS1256_DRATE_10SPS
  // ADS1256_DRATE_5SPS
  // ADS1256_DRATE_2_5SPS
  // 
  // NOTE : Data Rate vary depending on crystal frequency. Data rates listed below assumes the crystal frequency is 7.68Mhz
  //        for other frequency consult the datasheet.

  adc.begin(ADS1256_DRATE_30000SPS,ADS1256_GAIN_1,false);
  Serial.println("ADC Started");
  
  // Set MUX Register to AINO and AIN1
  adc.switchChannel(0);
}

void loop()
{ 

  for(int i=1;  i<=lo; i++){
  adc.waitDRDY(); // wait for DRDY to go low before changing multiplexer register
  adc.switchChannel(0);
  sensor1 = adc.readCurrentChannel(); // DOUT arriving here are from MUX AIN0 and AIN1  
  //Serial.println(sensor1,10);
  myarray[i] = sensor1;
 delayMicroseconds(150);
   // delay(1);
  }

   for(int n=1;  n<=lo; n++){
   sensor1 = myarray[n];
   Serial.println(sensor1,10) ;
 // Serial.print("\t");
  delay(50);
  }

  //print the result.
  //Serial.print("data sensor 1: ");
  //Serial.print(sensor1,10);
 
  //Serial.println("");
  
  delay(24000);
}`

Error Message

> In file included from C:\Users\kamil\Documents\Arduino\libraries\ADS1256\ADS1256.cpp:7:0:
> 
> C:\Users\kamil\Documents\Arduino\libraries\ADS1256\ADS1256.h:11:16: error: expected unqualified-id before numeric constant
> 
>  #define STATUS 0x00
> 
>                 ^
> 
> C:\Users\kamil\Documents\Arduino\hardware\espressif\esp32/tools/sdk/include/esp32/rom/ets_sys.h:614:3: note: in expansion of macro 'STATUS'
> 
>  } STATUS;
> 
>    ^
> 
> exit status 1
> Error compiling for board ESP32 Dev Module.
>

**Comment by Flydroid** [comment]
Are you sure that you are using this library?

The usage of this library is very much different than your sketch.
Please have a look at my example: https://github.com/Flydroid/ADS12xx-Library/blob/master/AD1248-Library.ino
