### ISSUE TITLE
[Question] How to use it with ESP32 ?

### ISSUE THREAD

**Issue by YordanYanakiev** [Flydroid/ADS12xx-Library#6]
Hello. 
Is it possible to use it with ESP32 boards, and if it is - could You give a glimpse about wiring it?
Thank You in advance.

**Comment by Flydroid** [comment]
Hi Yordan,
I haven't worked with a ESP32 myself yet. If it supports the typical Arduino functions including SPI the library should work. 
The wiring uses the typical SPI pins, MISO, MOSI, SCLK, SS in addition to DRDY, START, Pin on any digital input pin.
https://cdn.sparkfun.com/assets/learn_tutorials/5/0/7/esp32-thing-graphical-datasheet-v02.png

**Comment by YordanYanakiev** [comment]
Thank You kindly for Your fast response.
Just wanna be sure before start wiring it since the pinout names is different somehow and..
This is my board: https://www.ebay.com/itm/ADS1256-24-Bit-ADC-AD-Module-High-precision-ADC-Data-Acquisition-Board/132599868398?hash=item1edf916bee%3Ag%3AFzAAAOSwb5JbI8sF%3Ark%3A3%3Apf%3A0&fbclid=IwAR36EzYFHG_MrxqpUPcsDFJlorL4bGxZ4GvAZhBy3tKTfQlA459KUKticlY

and this is the pinout from behind 
![ads1256-24-bit-8-channel-adc-ad-module-high-precision-adc-data-acquisition](https://user-images.githubusercontent.com/6534199/47846749-a9b64c00-ddd1-11e8-8bde-9569a3471821.jpg)

**Comment by Flydroid** [comment]
I would recommend reading a little about how SPI works, that will help you
with the troubleshooting.

MISO = Master In Slave Out -> Connect to DOUT
MOSI = Master Out Slave In -> Connect DIN

Am Do., 1. Nov. 2018 um 11:29 Uhr schrieb Yordan Yanakiev <
notifications@github.com>:

**Comment by YordanYanakiev** [comment]
Adapted it more or less to ESP32, but unfortunately it keep restarting by reason unknown even without attached the ADS1256.

**Comment by YordanYanakiev** [comment]
maybe I have misunderstod the initialization.

> 
> 	ADS.begin( CS, START, DRDY, _RESET );  //initialize ADS as object of the ads12xx class
> 	ADS.Reset();

Since here is causing the nonstop reset I wonder what constants shall I put in my case in there ?

**Comment by Flydroid** [comment]
Hello Yordan, 
sorry for the late answer, the constants CS, START, DRDY and _RESET are pin numbers.
