### ISSUE TITLE
attachInterrupt() on Nano

### ISSUE THREAD

**Issue by Sapphire055** [Flydroid/ADS12xx-Library#8]
For ads12xx::begin(); in the attachInterrupt() function, you need to call digitalPinToInterrupt().

Without it the ISR isn't called.

The following modified code works on an Arduino Nano. 

attachInterrupt(digitalPinToInterrupt(_DRDY), DRDY_Interuppt, FALLING); //Interrupt setup for DRDY detection

Thanks

**Comment by Flydroid** [comment]
Thanks a lot!
I have updated that line!
